using Exafmmt_jll
using LinearAlgebra
using LinearMaps

abstract type FMMOptions end

"""
    HelmholtzFMMOptions{I, C} <: FMMOptions

Helmholtz initializer for the setup function.

# Fields

  - `p::I`: Multipole expansion order.
  - `ncrit::I`: Minimum number of points in each box of the tree.
  - `wavek::C`: Wavenumber.
"""
struct HelmholtzFMMOptions{I,C} <: FMMOptions
    p::I
    ncrit::I
    wavek::C
end

function HelmholtzFMMOptions(wavek::C; p=8, ncrit=100) where {C<:Complex}
    return HelmholtzFMMOptions(p, ncrit, wavek)
end

"""
    ModifiedHelmholtzFMMOptions{I, F} <: FMMOptions

Modified-Helmholtz initializer for the setup function.

# Fields

  - `p::I`: Multipole expansion order.
  - `ncrit::I`: Minimum number of points in each box of the tree.
  - `wavek::F`: Wavenumber.
"""
struct ModifiedHelmholtzFMMOptions{I,F} <: FMMOptions
    p::I
    ncrit::I
    wavek::F
end

function ModifiedHelmholtzFMMOptions(wavek::F; p=8, ncrit=100) where {F<:Real}
    return ModifiedHelmholtzFMMOptions(p, ncrit, wavek)
end

"""
    LaplaceFMMOptions{I} <: FMMOptions

Laplace initializer for the setup function.

# Fields

  - `p::I`: Multipole expansion order.
  - `ncrit::I`: Minimum number of points in each box of the tree.
"""
struct LaplaceFMMOptions{I} <: FMMOptions
    p::I
    ncrit::I
end

function LaplaceFMMOptions(; p=8, ncrit=100)
    return LaplaceFMMOptions(p, ncrit)
end

function validate_points(points::AbstractMatrix, name::AbstractString)
    size(points, 2) == 3 ||
        throw(ArgumentError("$name must be an n x 3 matrix of 3D points")) # COV_EXCL_LINE
    eltype(points) in (Float32, Float64) || throw(
        ArgumentError(
            "$name must have element type Float32 or Float64; got $(eltype(points))"
        ),
    ) # COV_EXCL_LINE
    return nothing
end

function validate_options(options::FMMOptions)
    options.p isa Integer || throw(ArgumentError("p must be an integer")) # COV_EXCL_LINE
    options.ncrit isa Integer || throw(ArgumentError("ncrit must be an integer")) # COV_EXCL_LINE
    options.p > 0 || throw(ArgumentError("p must be positive")) # COV_EXCL_LINE
    options.ncrit > 0 || throw(ArgumentError("ncrit must be positive")) # COV_EXCL_LINE
    options.p <= typemax(Cint) || throw(ArgumentError("p must fit in Cint")) # COV_EXCL_LINE
    options.ncrit <= typemax(Cint) || throw(ArgumentError("ncrit must fit in Cint")) # COV_EXCL_LINE
    return nothing
end

function validate_setup_inputs(
    sources::AbstractMatrix, targets::AbstractMatrix, options::FMMOptions
)
    validate_points(sources, "sources")
    validate_points(targets, "targets")
    validate_options(options)
    return nothing
end

function setup(sources::Matrix{<:Real}, targets::Matrix{<:Real}, fmmoptions::FMMOptions)
    eltype(sources) === eltype(targets) ||
        throw(ArgumentError("sources and targets must have the same element type")) # COV_EXCL_LINE
    validate_points(sources, "sources")
    validate_points(targets, "targets")
    validate_options(fmmoptions)
    return throw(
        ArgumentError(
            "unsupported combination of coordinate type $(eltype(sources)) and FMM options $(typeof(fmmoptions))",
        ),
    ) # COV_EXCL_LINE
end

"""
    ExaFMM{K, O} <: LinearMaps.LinearMap{K}

Represents an FMM matrix and can be multiplied by a vector containing the source charges.
This type owns C++ storage and releases it through `close!` or its finalizer.

# Fields

  - `fmmoptions::FMMOptions`: Initializer, either `LaplaceFMMOptions`, `HelmholtzFMMOptions`, or `ModifiedHelmholtzFMMOptions`.
  - `nsources::Int`: Number of sources.
  - `ntargets::Int`: Number of targets.
  - `fmm::Ptr{Cvoid}`: Pointer to the FMM struct generated by the C++ part.
  - `fmmstruct::Ptr{Cvoid}`: Pointer to a struct with the required C++ substructs.
  - `sources::Ptr{Cvoid}`: Pointer to the C++ struct of the sources.
  - `targets::Ptr{Cvoid}`: Pointer to the C++ struct of the targets.
"""
mutable struct ExaFMM{K,O<:FMMOptions} <: LinearMaps.LinearMap{K}
    fmmoptions::O
    nsources::Int
    ntargets::Int
    fmm::Ptr{Cvoid}
    fmmstruct::Ptr{Cvoid}
    sources::Ptr{Cvoid}
    targets::Ptr{Cvoid}
    closed::Bool
end

function ExaFMM{K}(
    fmmoptions::O,
    nsources::Integer,
    ntargets::Integer,
    fmm::Ptr{Cvoid},
    fmmstruct::Ptr{Cvoid},
    sources::Ptr{Cvoid},
    targets::Ptr{Cvoid},
) where {K,O<:FMMOptions}
    exafmm = ExaFMM{K,O}(
        fmmoptions, Int(nsources), Int(ntargets), fmm, fmmstruct, sources, targets, false
    )
    finalizer(close!, exafmm)
    return exafmm
end

function check_open(x::ExaFMM)
    x.closed && throw(ArgumentError("ExaFMM object is closed")) # COV_EXCL_LINE
    return nothing
end

"""
    close!(x::ExaFMM)

Release the C++ storage owned by `x`.

Calling `close!` more than once is safe. Closed objects cannot be evaluated or
multiplied again.
"""
function close!(x::ExaFMM)
    x.closed && return nothing

    if x.fmmstruct != C_NULL
        if x isa ExaFMM{<:Union{Float32,Float64}}
            freeF!(x)
        else
            freeC!(x)
        end
    end

    x.fmm = C_NULL
    x.fmmstruct = C_NULL
    x.sources = C_NULL
    x.targets = C_NULL
    x.closed = true

    return nothing
end

Base.close(x::ExaFMM) = close!(x)
Base.eltype(::Type{<:ExaFMM{K}}) where {K} = K
Base.eltype(::ExaFMM{K}) where {K} = K

function validate_charges(A::ExaFMM, x::AbstractVector)
    length(x) == A.nsources || throw(
        DimensionMismatch(
            "charge vector length $(length(x)) does not match number of sources $(A.nsources)",
        ),
    ) # COV_EXCL_LINE
    return nothing
end

# COV_EXCL_START
function evaluate(A::ExaFMM{K}, x::AbstractVector, fmmoptions::FMMOptions) where {K}
    check_open(A)
    validate_charges(A, x)
    return throw(
        ArgumentError(
            "unsupported evaluate call for ExaFMM{$K}, charges $(eltype(x)), and options $(typeof(fmmoptions))",
        ),
    ) # COV_EXCL_LINE
end
# COV_EXCL_STOP

"""
    freeF!(x::ExaFMM{Float64})

Frees the storage which is allocated by the C++ part for the Laplace-FMM and Modified-Helmholtz-FMM.

# Arguments

  - `x::ExaFMM{Float64}`: ExaFMM structure with pointers to all allocated variables.
"""
function freeF!(x::ExaFMM{Float64})
    return ccall(
        (:freestorage_real, libExafmm64),
        Cvoid,
        (Ptr{Cvoid}, Ptr{Cvoid}, Ptr{Cvoid}, Ptr{Cvoid}),
        x.fmm,
        x.fmmstruct,
        x.sources,
        x.targets,
    )
end

"""
    freeF!(x::ExaFMM{Float32})

Frees the storage which is allocated by the C++ part for the Laplace-FMM and Modified-Helmholtz-FMM.

# Arguments

  - `x::ExaFMM{Float32}`: ExaFMM structure with pointers to all allocated variables.
"""
function freeF!(x::ExaFMM{Float32})
    return ccall(
        (:freestorage_real, libExafmm32),
        Cvoid,
        (Ptr{Cvoid}, Ptr{Cvoid}, Ptr{Cvoid}, Ptr{Cvoid}),
        x.fmm,
        x.fmmstruct,
        x.sources,
        x.targets,
    )
end

"""
    freeC!(x::ExaFMM{ComplexF64})

Frees the storage which is allocated by the C++ part for Helmholtz-FMM.

# Arguments

  - `x::ExaFMM{ComplexF64}`: ExaFMM structure with pointers to all allocated variables.
"""
function freeC!(x::ExaFMM{ComplexF64})
    return ccall(
        (:freestorage_cplx, libExafmm64),
        Cvoid,
        (Ptr{Cvoid}, Ptr{Cvoid}, Ptr{Cvoid}, Ptr{Cvoid}),
        x.fmm,
        x.fmmstruct,
        x.sources,
        x.targets,
    )
end

"""
    freeC!(x::ExaFMM{ComplexF32})

Frees the storage which is allocated by the C++ part for Helmholtz-FMM.

# Arguments

  - `x::ExaFMM{ComplexF64}`: ExaFMM structure with pointers to all allocated variables.
"""
function freeC!(x::ExaFMM{ComplexF32})
    return ccall(
        (:freestorage_cplx, libExafmm32),
        Cvoid,
        (Ptr{Cvoid}, Ptr{Cvoid}, Ptr{Cvoid}, Ptr{Cvoid}),
        x.fmm,
        x.fmmstruct,
        x.sources,
        x.targets,
    )
end

function Base.size(fmm::ExaFMM, dim=nothing)
    if dim === nothing
        return (fmm.ntargets, fmm.nsources)
    elseif dim == 1
        return fmm.ntargets
    elseif dim == 2
        return fmm.nsources
    else
        throw(ArgumentError("dim must be either 1 or 2")) # COV_EXCL_LINE
    end
end

function wrap_c_result(ptr::Ptr{T}, len::Integer) where {T}
    ptr == C_NULL && error("ExaFMMt returned a null result pointer") # COV_EXCL_LINE
    # Exafmmt_jll v0.1.1 allocates these buffers with C++ new[] but exports no
    # matching deallocator, so Julia must not take ownership with own=true.
    return copy(unsafe_wrap(Array, ptr, len; own=false))
end

@views function LinearMaps._unsafe_mul!(y::AbstractVecOrMat, A::ExaFMM, x::AbstractVector)
    check_open(A)

    result = evaluate(A, x, A.fmmoptions)
    potential = view(result, :, 1)

    if y isa AbstractVector
        copyto!(y, potential)
    elseif size(y, 2) == 1
        copyto!(view(y, :, 1), potential)
    else
        throw(DimensionMismatch("output must be a vector or a single-column matrix")) # COV_EXCL_LINE
    end

    return y
end

@views function LinearMaps._unsafe_mul!(
    y::AbstractVecOrMat, transA::LinearMaps.TransposeMap{<:Any,<:ExaFMM}, x::AbstractVector
)
    return throw(
        ArgumentError(
            "transpose multiplication is not implemented for ExaFMM; build a new FMM with sources and targets swapped if you need the transposed operator",
        ),
    ) # COV_EXCL_LINE
end

@views function LinearMaps._unsafe_mul!(
    y::AbstractVecOrMat, transA::LinearMaps.AdjointMap{<:Any,<:ExaFMM}, x::AbstractVector
)
    return throw(
        ArgumentError(
            "adjoint multiplication is not implemented for ExaFMM; build an appropriate swapped/conjugated FMM explicitly",
        ),
    ) # COV_EXCL_LINE
end

"""
    init_sources(points::Matrix{F}, charges::Vector{F}) where F <: Real

Creates struct for sources and charges in the C++ part from the Julia matrix.
Real charges are used and mandatory for the Laplace- and Modified-Helmholtz-FMM.

# Arguments

  - `points::Matrix{F}`: 3d-coordinates of sources.
  - `charges::Vector{F}`: Values of for example the charge at each source location.
"""
function init_sources(points::Matrix{F}, charges::Vector{F}) where {F<:Real}
    validate_points(points, "sources")
    length(charges) == size(points, 1) ||
        throw(DimensionMismatch("charges and sources must have the same length")) # COV_EXCL_LINE

    return init_src(points, charges)
end

function init_src(points::Matrix{Float64}, charges::Vector{Float64})
    return ccall(
        (:init_sources_F, libExafmm64),
        Ptr{Cvoid},
        (Ptr{Float64}, Ptr{Float64}, Cint),
        vec(points),
        charges,
        length(charges),
    )
end

function init_src(points::Matrix{Float32}, charges::Vector{Float32})
    return ccall(
        (:init_sources_F, libExafmm32),
        Ptr{Cvoid},
        (Ptr{Float32}, Ptr{Float32}, Cint),
        vec(points),
        charges,
        length(charges),
    )
end

"""
    init_sources(points::Matrix{F}, charges::Vector{C}) where {F <: Real, C <: Complex}

Creates struct for sources and charges in the C++ part from the Julia matrix.
Complex charges are used for the Helmholtz-FMM.

# Arguments

  - `points::Matrix{F}`: 3d-coordinates of sources.
  - `charges::Vector{C}`: Values of for example the charge at each source location.
"""
function init_sources(points::Matrix{F}, charges::Vector{C}) where {F<:Real,C<:Complex}
    validate_points(points, "sources")
    C === Complex{F} || throw(
        ArgumentError("complex charge type $C must be Complex{$F} for $F coordinates")
    ) # COV_EXCL_LINE
    length(charges) == size(points, 1) ||
        throw(DimensionMismatch("charges and sources must have the same length")) # COV_EXCL_LINE

    return init_src(points, charges)
end

function init_src(points::Matrix{Float64}, charges::Vector{ComplexF64})
    return ccall(
        (:init_sources_C, libExafmm64),
        Ptr{Cvoid},
        (Ptr{Float64}, Ptr{ComplexF64}, Cint),
        vec(points),
        charges,
        length(charges),
    )
end

function init_src(points::Matrix{Float32}, charges::Vector{ComplexF32})
    return ccall(
        (:init_sources_C, libExafmm32),
        Ptr{Cvoid},
        (Ptr{Float32}, Ptr{ComplexF32}, Cint),
        vec(points),
        charges,
        length(charges),
    )
end

"""
    init_targets(points::Matrix{F}, T::Type) where F <: Real

Creates struct for targets in the C++ part from a Julia matrix of points.

# Arguments

  - `points::Matrix{C}`: 3d-coordinates of targets.
  - `T`: Type must be set for the Helmholtz-FMM to ComplexF32 or ComplexF64.
"""
function init_targets(points::Matrix{F}, T::Type) where {F<:Real}
    validate_points(points, "targets")

    if T == F
        return init_trgF(points)
    elseif T == Complex{F}
        return init_trgC(points)
    else
        # COV_EXCL_START
        throw(
            ArgumentError(
                "target value type $T must be $F or Complex{$F} for $F coordinates"
            ),
        )
        # COV_EXCL_STOP
    end
end

function init_trgC(points::Matrix{Float64})
    return ccall(
        (:init_targets_C, libExafmm64),
        Ptr{Cvoid},
        (Ptr{Float64}, Cint),
        vec(points),
        size(points)[1],
    )
end

function init_trgC(points::Matrix{Float32})
    return ccall(
        (:init_targets_C, libExafmm32),
        Ptr{Cvoid},
        (Ptr{Float32}, Cint),
        vec(points),
        size(points)[1],
    )
end

function init_trgF(points::Matrix{Float64})
    return ccall(
        (:init_targets_F, libExafmm64),
        Ptr{Cvoid},
        (Ptr{Float64}, Cint),
        vec(points),
        size(points)[1],
    )
end

function init_trgF(points::Matrix{Float32})
    return ccall(
        (:init_targets_F, libExafmm32),
        Ptr{Cvoid},
        (Ptr{Float32}, Cint),
        vec(points),
        size(points)[1],
    )
end

"""
    update_charges(fmmstruct::Ptr{Cvoid}, charges::Vector{Float64})

Updates charges in an already generated Laplace or Modified-Helmholtz-FMM.
Requires a Float64 array of charges.

# Arguments

  - `fmmstruct::Ptr{Cvoid}`: Pointer to a struct with the required C++ substructs.
  - `charges::Vector{Float64}`: Values of for example the charge at each source location.
"""
function update_charges(fmmstruct::Ptr{Cvoid}, charges::Vector{Float64})
    return ccall(
        (:update_charges_real, libExafmm64),
        Cvoid,
        (Ptr{Cvoid}, Ptr{Float64}),
        fmmstruct,
        charges,
    )
end

"""
    update_charges(fmmstruct::Ptr{Cvoid}, charges::Vector{Float32})

Updates charges in an already generated Laplace or Modified-Helmholtz-FMM.
Requires a Float32 array of charges.

# Arguments

  - `fmmstruct::Ptr{Cvoid}`: Pointer to a struct with the required C++ substructs.
  - `charges::Vector{Float32}`: Values of for example the charge at each source location.
"""
function update_charges(fmmstruct::Ptr{Cvoid}, charges::Vector{Float32})
    return ccall(
        (:update_charges_real, libExafmm32),
        Cvoid,
        (Ptr{Cvoid}, Ptr{Float32}),
        fmmstruct,
        charges,
    )
end

"""
    update_charges(fmmstruct::Ptr{Cvoid}, charges::Vector{ComplexF64})

Updates charges in already generated Helmholtz-FMM.
Requires a ComplexF64 array of charges.

# Arguments

  - `fmmstruct::Ptr{Cvoid}`: Pointer to a struct with the required C++ substructs.
  - `charges::Vector{ComplexF64}`: Values of for example the charge at each source location.
"""
function update_charges(fmmstruct::Ptr{Cvoid}, charges::Vector{ComplexF64})
    return ccall(
        (:update_charges_cplx, libExafmm64),
        Cvoid,
        (Ptr{Cvoid}, Ptr{ComplexF64}),
        fmmstruct,
        charges,
    )
end

"""
    update_charges(fmmstruct::Ptr{Cvoid}, charges::Vector{ComplexF32})

Updates charges in already generated Helmholtz-FMM.
Requires a ComplexF32 array of charges.

# Arguments

  - `fmmstruct::Ptr{Cvoid}`: Pointer to a struct with the required C++ substructs.
  - `charges::Vector{ComplexF32}`: Values of for example the charge at each source location.
"""
function update_charges(fmmstruct::Ptr{Cvoid}, charges::Vector{ComplexF32})
    return ccall(
        (:update_charges_cplx, libExafmm32),
        Cvoid,
        (Ptr{Cvoid}, Ptr{ComplexF32}),
        fmmstruct,
        charges,
    )
end

"""
    clear_values(fmmstruct::Ptr{Cvoid}, T::Type{Float64})

Clears the solution values in the FMM structure.

# Arguments

  - `fmmstruct::Ptr{Cvoid}`: Pointer to a struct with the required C++ substructs.
  - `T`: Type must be `ComplexF32` or `ComplexF64` for Helmholtz-FMM and `Float32` or `Float64` for Laplace or Modified-Helmholtz-FMM.
"""
function clear_values(fmmstruct::Ptr{Cvoid}, T::Type{Float64})
    return ccall((:clear_values, libExafmm64), Cvoid, (Ptr{Cvoid},), fmmstruct)
end

"""
    clear_values(fmmstruct::Ptr{Cvoid}, T::Type{Float32})

Clears the solution values in the FMM structure.

# Arguments

  - `fmmstruct::Ptr{Cvoid}`: Pointer to a struct with the required C++ substructs.
  - `T`: Type must be `ComplexF32` or `ComplexF64` for Helmholtz-FMM and `Float32` or `Float64` for Laplace or Modified-Helmholtz-FMM.
"""
function clear_values(fmmstruct::Ptr{Cvoid}, T::Type{Float32})
    return ccall((:clear_values, libExafmm32), Cvoid, (Ptr{Cvoid},), fmmstruct)
end

"""
    clear_values(fmmstruct::Ptr{Cvoid}, T::Type{ComplexF64})

Clears the solution values in the FMM structure.

# Arguments

  - `fmmstruct::Ptr{Cvoid}`: Pointer to a struct with the required C++ substructs.
  - `T`: Type must be `ComplexF32` or `ComplexF64` for Helmholtz-FMM and `Float32` or `Float64` for Laplace or Modified-Helmholtz-FMM.
"""
function clear_values(fmmstruct::Ptr{Cvoid}, T::Type{ComplexF64})
    return ccall((:clear_values, libExafmm64), Cvoid, (Ptr{Cvoid},), fmmstruct)
end

"""
    clear_values(fmmstruct::Ptr{Cvoid}, T::Type{ComplexF32})

Clears the solution values in the FMM structure.

# Arguments

  - `fmmstruct::Ptr{Cvoid}`: Pointer to a struct with the required C++ substructs.
  - `T`: Type must be `ComplexF32` or `ComplexF64` for Helmholtz-FMM and `Float32` or `Float64` for Laplace or Modified-Helmholtz-FMM.
"""
function clear_values(fmmstruct::Ptr{Cvoid}, T::Type{ComplexF32})
    return ccall((:clear_values, libExafmm32), Cvoid, (Ptr{Cvoid},), fmmstruct)
end
